version: '3'
services:
  dinoes-be-prod:
    container_name: dinoes-be-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8700:8700'
    volumes:
      - .:/src:cached